// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rcapis/api/label.proto

package label

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Value types that can be used as label values.
type LabelDescriptor_ValueType int32

const (
	// A variable-length string. This is the default.
	LabelDescriptor_STRING LabelDescriptor_ValueType = 0
	// Boolean; true or false.
	LabelDescriptor_BOOL LabelDescriptor_ValueType = 1
	// A 64-bit signed integer.
	LabelDescriptor_INT64 LabelDescriptor_ValueType = 2
)

var LabelDescriptor_ValueType_name = map[int32]string{
	0: "STRING",
	1: "BOOL",
	2: "INT64",
}

var LabelDescriptor_ValueType_value = map[string]int32{
	"STRING": 0,
	"BOOL":   1,
	"INT64":  2,
}

func (x LabelDescriptor_ValueType) String() string {
	return proto.EnumName(LabelDescriptor_ValueType_name, int32(x))
}

func (LabelDescriptor_ValueType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_18fe712c9bf4d7b9, []int{0, 0}
}

// A description of a label.
type LabelDescriptor struct {
	// The label key.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// The type of data that can be assigned to the label.
	ValueType LabelDescriptor_ValueType `protobuf:"varint,2,opt,name=value_type,json=valueType,proto3,enum=rcrai.api.LabelDescriptor_ValueType" json:"value_type,omitempty"`
	// A human-readable description for the label.
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LabelDescriptor) Reset()         { *m = LabelDescriptor{} }
func (m *LabelDescriptor) String() string { return proto.CompactTextString(m) }
func (*LabelDescriptor) ProtoMessage()    {}
func (*LabelDescriptor) Descriptor() ([]byte, []int) {
	return fileDescriptor_18fe712c9bf4d7b9, []int{0}
}

func (m *LabelDescriptor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LabelDescriptor.Unmarshal(m, b)
}
func (m *LabelDescriptor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LabelDescriptor.Marshal(b, m, deterministic)
}
func (m *LabelDescriptor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LabelDescriptor.Merge(m, src)
}
func (m *LabelDescriptor) XXX_Size() int {
	return xxx_messageInfo_LabelDescriptor.Size(m)
}
func (m *LabelDescriptor) XXX_DiscardUnknown() {
	xxx_messageInfo_LabelDescriptor.DiscardUnknown(m)
}

var xxx_messageInfo_LabelDescriptor proto.InternalMessageInfo

func (m *LabelDescriptor) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *LabelDescriptor) GetValueType() LabelDescriptor_ValueType {
	if m != nil {
		return m.ValueType
	}
	return LabelDescriptor_STRING
}

func (m *LabelDescriptor) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterEnum("rcrai.api.LabelDescriptor_ValueType", LabelDescriptor_ValueType_name, LabelDescriptor_ValueType_value)
	proto.RegisterType((*LabelDescriptor)(nil), "rcrai.api.LabelDescriptor")
}

func init() { proto.RegisterFile("rcapis/api/label.proto", fileDescriptor_18fe712c9bf4d7b9) }

var fileDescriptor_18fe712c9bf4d7b9 = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0x4a, 0x4e, 0x2c,
	0xc8, 0x2c, 0xd6, 0x4f, 0x2c, 0xc8, 0xd4, 0xcf, 0x49, 0x4c, 0x4a, 0xcd, 0xd1, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0xe2, 0x2c, 0x4a, 0x2e, 0x4a, 0xcc, 0xd4, 0x4b, 0x2c, 0xc8, 0x54, 0xda, 0xc1,
	0xc8, 0xc5, 0xef, 0x03, 0x92, 0x72, 0x49, 0x2d, 0x4e, 0x2e, 0xca, 0x2c, 0x28, 0xc9, 0x2f, 0x12,
	0x12, 0xe0, 0x62, 0xce, 0x4e, 0xad, 0x94, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0x31, 0x85,
	0x9c, 0xb9, 0xb8, 0xca, 0x12, 0x73, 0x4a, 0x53, 0xe3, 0x4b, 0x2a, 0x0b, 0x52, 0x25, 0x98, 0x14,
	0x18, 0x35, 0xf8, 0x8c, 0x54, 0xf4, 0xe0, 0xa6, 0xe8, 0xa1, 0x99, 0xa0, 0x17, 0x06, 0x52, 0x1c,
	0x52, 0x59, 0x90, 0x1a, 0xc4, 0x59, 0x06, 0x63, 0x0a, 0x29, 0x70, 0x71, 0xa7, 0x40, 0x95, 0x64,
	0xe6, 0xe7, 0x49, 0x30, 0x83, 0x8d, 0x47, 0x16, 0x52, 0xd2, 0xe1, 0xe2, 0x84, 0xeb, 0x14, 0xe2,
	0xe2, 0x62, 0x0b, 0x0e, 0x09, 0xf2, 0xf4, 0x73, 0x17, 0x60, 0x10, 0xe2, 0xe0, 0x62, 0x71, 0xf2,
	0xf7, 0xf7, 0x11, 0x60, 0x14, 0xe2, 0xe4, 0x62, 0xf5, 0xf4, 0x0b, 0x31, 0x33, 0x11, 0x60, 0x72,
	0x8a, 0xe2, 0x12, 0x49, 0xce, 0xcf, 0x85, 0xba, 0x02, 0xe2, 0x53, 0x90, 0x63, 0x9c, 0x78, 0x3d,
	0x4a, 0x4a, 0x0a, 0x9c, 0xf2, 0x53, 0x2a, 0x03, 0x40, 0x9e, 0x0d, 0x60, 0x8c, 0xd2, 0x4b, 0xcf,
	0x2c, 0xc9, 0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x07, 0xab, 0xd6, 0x87, 0x86, 0x0b, 0x7a,
	0xf0, 0x58, 0x83, 0xc9, 0x1f, 0x8c, 0x8c, 0x49, 0x6c, 0xe0, 0x80, 0x32, 0x06, 0x04, 0x00, 0x00,
	0xff, 0xff, 0x8f, 0x8a, 0x26, 0xb1, 0x42, 0x01, 0x00, 0x00,
}
